In [1]:
import pandas as pd

In [4]:
data={'Name':['Alice','Bob'],'Age':[25,30]}

In [5]:
df=pd.DataFrame(data)

In [6]:
lst=[['Alice',25],['Bob',30]]

In [7]:
df=pd.DataFrame(lst,columns=['Name','Age'])

In [8]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [9]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [11]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [12]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [13]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [14]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [15]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [16]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [17]:
df['Gender']=['F','M']

In [18]:
df.drop('Age',axis=1,inplace=True)

In [19]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [20]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [22]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

df.groupby('Gender')['Age'].mean()

In [66]:
df1=pd.DataFrame({'key': [1, 2, 3],'Name': ['Alice', 'Bob', 'Charlie']})

In [67]:
df2=pd.DataFrame({'key':[1,2,3],'Age':[25,30,35]})

In [68]:
pd.merge(df1,df2,on='key')

   key     Name  Age
0    1    Alice   25
1    2      Bob   30
2    3  Charlie   35

In [69]:
df1.join(df2, lsuffix='_left', rsuffix='_right')

   key_left     Name  key_right  Age
0         1    Alice          1   25
1         2      Bob          2   30
2         3  Charlie          3   35

In [70]:
df=pd.read_csv("C:/Users/shrey/OneDrive/Documents/datas.csv")

In [71]:
df.to_csv('output.csv', index=False)

In [72]:
df.sort_values('Age')

      Name  Age gender
0    Alice   20      f
3    Padma   21      f
1      Bob   26      m
2  Charlie   27      m
4  Himnshu   30      m

In [73]:
df['Age'].apply(lambda x: x + 1)

0    21
1    27
2    28
3    22
4    31
Name: Age, dtype: int64

In [74]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob', 'Charlie', 'Padma', 'Himnshu']
Length: 5, dtype: str

In [75]:
df['Age'].value_counts()

Age
20    1
26    1
27    1
21    1
30    1
Name: count, dtype: int64